version: "2"
linters:
  enable:
    - gosec
    - misspell
    - wrapcheck
  settings:
    staticcheck:
      checks:
        - all
        - -QF*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
          - wrapcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/xico42/codeherd
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
